export const UPDATE_CURRENT_SETPOINT = 'UPDATE_CURRENT_SETPOINT';

export const FETCH_TEMPERATURE_DATA_START = 'FETCH_TEMPERATURE_DATA_START';
export const FETCH_TEMPERATURE_DATA_SUCCESS = 'FETCH_TEMPERATURE_DATA_SUCCESS';
export const FETCH_TEMPERATURE_DATA_FAIL = 'FETCH_TEMPERATURE_DATA_FAIL';
